version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3307/demooauth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8mb4
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456

  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=demooauth
      - MYSQL_ROOT_PASSWORD=123456
    expose:
      - "3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
