# Copy this file to application-local.yml and update with your values
# DO NOT commit application-local.yml to git

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: key client-id
            client-secret: key client-secret
            scope:
              - email
              - profile
